/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module menu_3 (
    input clk,
    input rst,
    input left,
    input right,
    input up,
    input down,
    input [10:0] x,
    input [10:0] y,
    input i_animate,
    input on,
    output reg [4:0] o_x,
    output reg [4:0] o_y,
    output reg r,
    output reg g,
    output reg b
  );
  
  
  
  wire [5-1:0] M_selection_square_o_x;
  wire [5-1:0] M_selection_square_o_y;
  wire [1-1:0] M_selection_square_red;
  wire [1-1:0] M_selection_square_green;
  wire [1-1:0] M_selection_square_blue;
  reg [1-1:0] M_selection_square_reset;
  selection_square_9 selection_square (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .on(on),
    .right(right),
    .down(down),
    .up(up),
    .left(left),
    .i_animate(i_animate),
    .reset(M_selection_square_reset),
    .o_x(M_selection_square_o_x),
    .o_y(M_selection_square_o_y),
    .red(M_selection_square_red),
    .green(M_selection_square_green),
    .blue(M_selection_square_blue)
  );
  
  always @* begin
    if (on) begin
      M_selection_square_reset = 1'h0;
      r = M_selection_square_red;
      g = M_selection_square_green;
      b = M_selection_square_blue;
      o_x = M_selection_square_o_x;
      o_y = M_selection_square_o_y;
    end else begin
      M_selection_square_reset = 1'h0;
      r = 1'h0;
      g = 1'h0;
      b = 1'h0;
      o_x = 1'h0;
      o_y = 1'h0;
    end
  end
endmodule
