/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_119 (
    input [15:0] a,
    input [4:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'bxxxxxxxxxxxxxxxx;
    
    case (alufn)
      6'h20: begin
        out = a << b;
      end
      6'h21: begin
        out = a >> b;
      end
      6'h23: begin
        out = $signed(a) >>> b;
      end
    endcase
  end
endmodule
