/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module spike_11 (
    input clk,
    input rst,
    input [4:0] i_x,
    input [4:0] i_y,
    input [10:0] x,
    input [10:0] y,
    output reg red,
    output reg green,
    output reg blue,
    output reg active
  );
  
  
  
  reg [899:0] sq_figure;
  
  reg [10:0] start_x;
  
  reg [10:0] start_y;
  
  reg [4:0] sq_fig_x;
  
  reg [4:0] sq_fig_y;
  
  wire [11-1:0] M_umovingsquare_o_x1;
  wire [11-1:0] M_umovingsquare_o_x2;
  wire [11-1:0] M_umovingsquare_o_y1;
  wire [11-1:0] M_umovingsquare_o_y2;
  singleunmovingsquare_59 umovingsquare (
    .i_x(start_x),
    .i_y(start_y),
    .o_x1(M_umovingsquare_o_x1),
    .o_x2(M_umovingsquare_o_x2),
    .o_y1(M_umovingsquare_o_y1),
    .o_y2(M_umovingsquare_o_y2)
  );
  
  always @* begin
    red = 1'h0;
    green = 1'h0;
    blue = 1'h0;
    active = 1'h0;
    sq_figure[0+0+29-:30] = 30'h00000000;
    sq_figure[30+0+29-:30] = 30'h00008000;
    sq_figure[60+0+29-:30] = 30'h0000c000;
    sq_figure[90+0+29-:30] = 30'h0000c000;
    sq_figure[120+0+29-:30] = 30'h0001e000;
    sq_figure[150+0+29-:30] = 30'h0107f860;
    sq_figure[180+0+29-:30] = 30'h01ffffc0;
    sq_figure[210+0+29-:30] = 30'h00ffffc0;
    sq_figure[240+0+29-:30] = 30'h00fe1fc0;
    sq_figure[270+0+29-:30] = 30'h00f807c0;
    sq_figure[300+0+29-:30] = 30'h00f003c0;
    sq_figure[330+0+29-:30] = 30'h01e001e0;
    sq_figure[360+0+29-:30] = 30'h01e001e0;
    sq_figure[390+0+29-:30] = 30'h03c000f0;
    sq_figure[420+0+29-:30] = 30'h0fc000fe;
    sq_figure[450+0+29-:30] = 30'h1fc000fc;
    sq_figure[480+0+29-:30] = 30'h03c000f0;
    sq_figure[510+0+29-:30] = 30'h01e001e0;
    sq_figure[540+0+29-:30] = 30'h01e001e0;
    sq_figure[570+0+29-:30] = 30'h00f003c0;
    sq_figure[600+0+29-:30] = 30'h00f807c0;
    sq_figure[630+0+29-:30] = 30'h00fe1fc0;
    sq_figure[660+0+29-:30] = 30'h00ffffc0;
    sq_figure[690+0+29-:30] = 30'h00ffffe0;
    sq_figure[720+0+29-:30] = 30'h0187f820;
    sq_figure[750+0+29-:30] = 30'h0001e000;
    sq_figure[780+0+29-:30] = 30'h0000c000;
    sq_figure[810+0+29-:30] = 30'h0000c000;
    sq_figure[840+0+29-:30] = 30'h00004000;
    sq_figure[870+0+29-:30] = 30'h00000000;
    start_x = 5'h13 + i_x * 6'h28;
    start_y = 5'h13 + i_y * 6'h28;
    sq_fig_x = x - M_umovingsquare_o_x1 - 1'h1;
    sq_fig_y = y - M_umovingsquare_o_y1 - 1'h1;
    if (x > M_umovingsquare_o_x1 && x <= M_umovingsquare_o_x2 && y > M_umovingsquare_o_y1 && y <= M_umovingsquare_o_y2) begin
      if (sq_figure[(sq_fig_y)*30+(sq_fig_x)*1+0-:1] == 1'h1) begin
        red = 1'h1;
        green = 1'h1;
        blue = 1'h0;
        active = 1'h1;
      end else begin
        red = 1'h0;
        green = 1'h0;
        blue = 1'h0;
        active = 1'h0;
      end
    end
  end
endmodule
