/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_118 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  reg z;
  
  reg v;
  
  reg n;
  
  wire [16-1:0] M_adder_out;
  wire [1-1:0] M_adder_zOut;
  wire [1-1:0] M_adder_vOut;
  wire [1-1:0] M_adder_nOut;
  adder_116 adder (
    .a(a),
    .b(b),
    .alufn(6'h01),
    .out(M_adder_out),
    .zOut(M_adder_zOut),
    .vOut(M_adder_vOut),
    .nOut(M_adder_nOut)
  );
  
  always @* begin
    out = 8'bxxxxxxxx;
    z = M_adder_zOut;
    v = M_adder_vOut;
    n = M_adder_nOut;
    
    case (alufn)
      6'h33: begin
        out[0+0-:1] = z;
      end
      6'h35: begin
        out[0+0-:1] = n ^ v;
      end
      6'h37: begin
        out[0+0-:1] = z | (n ^ v);
      end
    endcase
  end
endmodule
