/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module level5_8 (
    input clk,
    input rst,
    input left,
    input right,
    input up,
    input down,
    input [10:0] x,
    input [10:0] y,
    input i_animate,
    input on,
    input change_ball,
    output reg r,
    output reg g,
    output reg b,
    output reg pass
  );
  
  
  
  reg pixel_tick;
  
  reg [159:0] grid_input;
  
  reg star_r;
  reg star_g;
  reg star_b;
  
  reg star1_r;
  reg star1_g;
  reg star1_b;
  
  reg star2_r;
  reg star2_g;
  reg star2_b;
  
  reg star3_r;
  reg star3_g;
  reg star3_b;
  
  reg star4_r;
  reg star4_g;
  reg star4_b;
  
  reg star5_r;
  reg star5_g;
  reg star5_b;
  
  reg star6_r;
  reg star6_g;
  reg star6_b;
  
  reg star7_r;
  reg star7_g;
  reg star7_b;
  
  reg star8_r;
  reg star8_g;
  reg star8_b;
  
  reg star9_r;
  reg star9_g;
  reg star9_b;
  
  reg star10_r;
  reg star10_g;
  reg star10_b;
  
  reg star11_r;
  reg star11_g;
  reg star11_b;
  
  reg ball_r;
  reg ball_g;
  reg ball_b;
  
  reg ball1_r;
  reg ball1_g;
  reg ball1_b;
  
  reg M_pixel_reg_d, M_pixel_reg_q = 1'h0;
  reg [159:0] M_grid_change_d, M_grid_change_q = 1'h0;
  reg [1:0] M_collision_d, M_collision_q = 1'h0;
  reg [1:0] M_collision1_d, M_collision1_q = 1'h0;
  reg [1:0] M_collision2_d, M_collision2_q = 1'h0;
  reg [1:0] M_collision3_d, M_collision3_q = 1'h0;
  reg [1:0] M_collision4_d, M_collision4_q = 1'h0;
  reg [1:0] M_collision5_d, M_collision5_q = 1'h0;
  reg [1:0] M_collision6_d, M_collision6_q = 1'h0;
  reg [1:0] M_collision7_d, M_collision7_q = 1'h0;
  reg [1:0] M_collision8_d, M_collision8_q = 1'h0;
  reg [1:0] M_collision9_d, M_collision9_q = 1'h0;
  reg [1:0] M_collision10_d, M_collision10_q = 1'h0;
  reg [1:0] M_collision11_d, M_collision11_q = 1'h0;
  reg [4:0] M_stars_d, M_stars_q = 1'h0;
  reg [23:0] M_counter_d, M_counter_q = 1'h0;
  reg [2:0] M_current_ball_d, M_current_ball_q = 1'h0;
  reg [1:0] M_ball01_collision_d, M_ball01_collision_q = 1'h0;
  reg [1:0] M_ball10_collision_d, M_ball10_collision_q = 1'h0;
  reg M_ball_destroyed_d, M_ball_destroyed_q = 1'h0;
  reg M_ball1_destroyed_d, M_ball1_destroyed_q = 1'h0;
  localparam IDLE_ball_selected = 1'd0;
  localparam CHANGING_ball_selected = 1'd1;
  
  reg M_ball_selected_d, M_ball_selected_q = IDLE_ball_selected;
  
  wire [1-1:0] M_ball_red;
  wire [1-1:0] M_ball_green;
  wire [1-1:0] M_ball_blue;
  wire [1-1:0] M_ball_active;
  wire [1-1:0] M_ball_moving;
  reg [160-1:0] M_ball_grid;
  reg [1-1:0] M_ball_on;
  reg [1-1:0] M_ball_reset;
  ball_10 ball (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h07),
    .i_y(5'h03),
    .up(up),
    .down(down),
    .left(left),
    .right(right),
    .i_animate(i_animate),
    .grid(M_ball_grid),
    .on(M_ball_on),
    .reset(M_ball_reset),
    .red(M_ball_red),
    .green(M_ball_green),
    .blue(M_ball_blue),
    .active(M_ball_active),
    .moving(M_ball_moving)
  );
  wire [1-1:0] M_ball1_red;
  wire [1-1:0] M_ball1_green;
  wire [1-1:0] M_ball1_blue;
  wire [1-1:0] M_ball1_active;
  wire [1-1:0] M_ball1_moving;
  reg [160-1:0] M_ball1_grid;
  reg [1-1:0] M_ball1_on;
  reg [1-1:0] M_ball1_reset;
  ball_10 ball1 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h0b),
    .i_y(5'h04),
    .up(up),
    .down(down),
    .left(left),
    .right(right),
    .i_animate(i_animate),
    .grid(M_ball1_grid),
    .on(M_ball1_on),
    .reset(M_ball1_reset),
    .red(M_ball1_red),
    .green(M_ball1_green),
    .blue(M_ball1_blue),
    .active(M_ball1_active),
    .moving(M_ball1_moving)
  );
  wire [1-1:0] M_star_red;
  wire [1-1:0] M_star_green;
  wire [1-1:0] M_star_blue;
  wire [1-1:0] M_star_active;
  star_12 star (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h05),
    .i_y(5'h02),
    .red(M_star_red),
    .green(M_star_green),
    .blue(M_star_blue),
    .active(M_star_active)
  );
  wire [1-1:0] M_star1_red;
  wire [1-1:0] M_star1_green;
  wire [1-1:0] M_star1_blue;
  wire [1-1:0] M_star1_active;
  star_12 star1 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h0a),
    .i_y(5'h02),
    .red(M_star1_red),
    .green(M_star1_green),
    .blue(M_star1_blue),
    .active(M_star1_active)
  );
  wire [1-1:0] M_star2_red;
  wire [1-1:0] M_star2_green;
  wire [1-1:0] M_star2_blue;
  wire [1-1:0] M_star2_active;
  star_12 star2 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h06),
    .i_y(5'h03),
    .red(M_star2_red),
    .green(M_star2_green),
    .blue(M_star2_blue),
    .active(M_star2_active)
  );
  wire [1-1:0] M_star3_red;
  wire [1-1:0] M_star3_green;
  wire [1-1:0] M_star3_blue;
  wire [1-1:0] M_star3_active;
  star_12 star3 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h09),
    .i_y(5'h03),
    .red(M_star3_red),
    .green(M_star3_green),
    .blue(M_star3_blue),
    .active(M_star3_active)
  );
  wire [1-1:0] M_star4_red;
  wire [1-1:0] M_star4_green;
  wire [1-1:0] M_star4_blue;
  wire [1-1:0] M_star4_active;
  star_12 star4 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h07),
    .i_y(5'h04),
    .red(M_star4_red),
    .green(M_star4_green),
    .blue(M_star4_blue),
    .active(M_star4_active)
  );
  wire [1-1:0] M_star5_red;
  wire [1-1:0] M_star5_green;
  wire [1-1:0] M_star5_blue;
  wire [1-1:0] M_star5_active;
  star_12 star5 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h08),
    .i_y(5'h04),
    .red(M_star5_red),
    .green(M_star5_green),
    .blue(M_star5_blue),
    .active(M_star5_active)
  );
  wire [1-1:0] M_star6_red;
  wire [1-1:0] M_star6_green;
  wire [1-1:0] M_star6_blue;
  wire [1-1:0] M_star6_active;
  star_12 star6 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h07),
    .i_y(5'h05),
    .red(M_star6_red),
    .green(M_star6_green),
    .blue(M_star6_blue),
    .active(M_star6_active)
  );
  wire [1-1:0] M_star7_red;
  wire [1-1:0] M_star7_green;
  wire [1-1:0] M_star7_blue;
  wire [1-1:0] M_star7_active;
  star_12 star7 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h08),
    .i_y(5'h05),
    .red(M_star7_red),
    .green(M_star7_green),
    .blue(M_star7_blue),
    .active(M_star7_active)
  );
  wire [1-1:0] M_star8_red;
  wire [1-1:0] M_star8_green;
  wire [1-1:0] M_star8_blue;
  wire [1-1:0] M_star8_active;
  star_12 star8 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h06),
    .i_y(5'h06),
    .red(M_star8_red),
    .green(M_star8_green),
    .blue(M_star8_blue),
    .active(M_star8_active)
  );
  wire [1-1:0] M_star9_red;
  wire [1-1:0] M_star9_green;
  wire [1-1:0] M_star9_blue;
  wire [1-1:0] M_star9_active;
  star_12 star9 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h09),
    .i_y(5'h06),
    .red(M_star9_red),
    .green(M_star9_green),
    .blue(M_star9_blue),
    .active(M_star9_active)
  );
  wire [1-1:0] M_star10_red;
  wire [1-1:0] M_star10_green;
  wire [1-1:0] M_star10_blue;
  wire [1-1:0] M_star10_active;
  star_12 star10 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h05),
    .i_y(5'h07),
    .red(M_star10_red),
    .green(M_star10_green),
    .blue(M_star10_blue),
    .active(M_star10_active)
  );
  wire [1-1:0] M_star11_red;
  wire [1-1:0] M_star11_green;
  wire [1-1:0] M_star11_blue;
  wire [1-1:0] M_star11_active;
  star_12 star11 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .i_x(5'h0a),
    .i_y(5'h07),
    .red(M_star11_red),
    .green(M_star11_green),
    .blue(M_star11_blue),
    .active(M_star11_active)
  );
  wire [1-1:0] M_grid_red;
  wire [1-1:0] M_grid_green;
  wire [1-1:0] M_grid_blue;
  reg [160-1:0] M_grid_grid;
  grid_16 grid (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .grid(M_grid_grid),
    .red(M_grid_red),
    .green(M_grid_green),
    .blue(M_grid_blue)
  );
  
  always @* begin
    M_ball_selected_d = M_ball_selected_q;
    M_collision1_d = M_collision1_q;
    M_ball10_collision_d = M_ball10_collision_q;
    M_collision10_d = M_collision10_q;
    M_collision11_d = M_collision11_q;
    M_counter_d = M_counter_q;
    M_grid_change_d = M_grid_change_q;
    M_ball_destroyed_d = M_ball_destroyed_q;
    M_ball01_collision_d = M_ball01_collision_q;
    M_pixel_reg_d = M_pixel_reg_q;
    M_ball1_destroyed_d = M_ball1_destroyed_q;
    M_stars_d = M_stars_q;
    M_current_ball_d = M_current_ball_q;
    M_collision2_d = M_collision2_q;
    M_collision3_d = M_collision3_q;
    M_collision4_d = M_collision4_q;
    M_collision5_d = M_collision5_q;
    M_collision6_d = M_collision6_q;
    M_collision7_d = M_collision7_q;
    M_collision8_d = M_collision8_q;
    M_collision_d = M_collision_q;
    M_collision9_d = M_collision9_q;
    
    M_pixel_reg_d = ~M_pixel_reg_q;
    pixel_tick = (M_pixel_reg_q == 1'h0);
    grid_input = 160'h00000d300810008000000000000008900c300000;
    M_grid_grid = M_grid_change_q;
    M_ball_grid = M_grid_change_q;
    M_ball1_grid = M_grid_change_q;
    M_counter_d = M_counter_q + 1'h1;
    if (on) begin
      M_grid_change_d = grid_input;
      M_stars_d = M_stars_q;
      M_ball_reset = 1'h0;
      M_ball1_reset = 1'h0;
      M_current_ball_d = M_current_ball_q;
      M_ball_destroyed_d = M_ball_destroyed_q;
      M_ball1_destroyed_d = M_ball1_destroyed_q;
      M_ball_on = 1'h0;
      M_ball1_on = 1'h0;
      
      case (M_ball_selected_q)
        IDLE_ball_selected: begin
          if (M_current_ball_q == 1'h0) begin
            M_ball_on = 1'h1;
            M_ball1_on = 1'h0;
          end else begin
            if (M_current_ball_q == 1'h1) begin
              M_ball_on = 1'h0;
              M_ball1_on = 1'h1;
            end
          end
          if (change_ball) begin
            M_counter_d = 1'h0;
            M_ball_selected_d = CHANGING_ball_selected;
          end
        end
        CHANGING_ball_selected: begin
          if (pixel_tick == 1'h1 && i_animate == 1'h1 && M_counter_q[23+0-:1] == 1'h1) begin
            if (M_ball1_destroyed_q == 1'h1) begin
              M_current_ball_d = 1'h0;
            end else begin
              if (M_ball_destroyed_q == 1'h1) begin
                M_current_ball_d = 1'h1;
              end else begin
                if (M_ball_destroyed_q == 1'h0 && M_ball1_destroyed_q == 1'h0) begin
                  if (M_current_ball_q == 1'h1) begin
                    M_current_ball_d = 1'h0;
                  end else begin
                    M_current_ball_d = M_current_ball_q + 1'h1;
                  end
                end
              end
            end
            M_ball_selected_d = IDLE_ball_selected;
          end
        end
      endcase
      if (M_collision_q == 1'h0) begin
        M_collision_d = M_ball_active & M_star_active | M_ball1_active & M_star_active;
        star_r = M_star_red;
        star_g = M_star_green;
        star_b = M_star_blue;
      end else begin
        if (M_collision_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision_d = M_collision_q + 1'h1;
          star_r = 1'h0;
          star_g = 1'h0;
          star_b = 1'h0;
        end else begin
          M_collision_d = M_collision_q;
          star_r = 1'h0;
          star_g = 1'h0;
          star_b = 1'h0;
        end
      end
      if (M_collision1_q == 1'h0) begin
        M_collision1_d = M_ball_active & M_star1_active | M_ball1_active & M_star1_active;
        star1_r = M_star1_red;
        star1_g = M_star1_green;
        star1_b = M_star1_blue;
      end else begin
        if (M_collision1_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision1_d = M_collision1_q + 1'h1;
          star1_r = 1'h0;
          star1_g = 1'h0;
          star1_b = 1'h0;
        end else begin
          M_collision1_d = M_collision1_q;
          star1_r = 1'h0;
          star1_g = 1'h0;
          star1_b = 1'h0;
        end
      end
      if (M_collision2_q == 1'h0) begin
        M_collision2_d = M_ball_active & M_star2_active | M_ball1_active & M_star2_active;
        star2_r = M_star2_red;
        star2_g = M_star2_green;
        star2_b = M_star2_blue;
      end else begin
        if (M_collision2_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision2_d = M_collision2_q + 1'h1;
          star2_r = 1'h0;
          star2_g = 1'h0;
          star2_b = 1'h0;
        end else begin
          M_collision2_d = M_collision2_q;
          star2_r = 1'h0;
          star2_g = 1'h0;
          star2_b = 1'h0;
        end
      end
      if (M_collision3_q == 1'h0) begin
        M_collision3_d = M_ball_active & M_star3_active | M_ball1_active & M_star3_active;
        star3_r = M_star3_red;
        star3_g = M_star3_green;
        star3_b = M_star3_blue;
      end else begin
        if (M_collision3_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision3_d = M_collision3_q + 1'h1;
          star3_r = 1'h0;
          star3_g = 1'h0;
          star3_b = 1'h0;
        end else begin
          M_collision3_d = M_collision3_q;
          star3_r = 1'h0;
          star3_g = 1'h0;
          star3_b = 1'h0;
        end
      end
      if (M_collision4_q == 1'h0) begin
        M_collision4_d = M_ball_active & M_star4_active | M_ball1_active & M_star4_active;
        star4_r = M_star4_red;
        star4_g = M_star4_green;
        star4_b = M_star4_blue;
      end else begin
        if (M_collision4_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision4_d = M_collision4_q + 1'h1;
          star4_r = 1'h0;
          star4_g = 1'h0;
          star4_b = 1'h0;
        end else begin
          M_collision4_d = M_collision4_q;
          star4_r = 1'h0;
          star4_g = 1'h0;
          star4_b = 1'h0;
        end
      end
      if (M_collision5_q == 1'h0) begin
        M_collision5_d = M_ball_active & M_star5_active | M_ball1_active & M_star5_active;
        star5_r = M_star5_red;
        star5_g = M_star5_green;
        star5_b = M_star5_blue;
      end else begin
        if (M_collision5_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision5_d = M_collision5_q + 1'h1;
          star5_r = 1'h0;
          star5_g = 1'h0;
          star5_b = 1'h0;
        end else begin
          M_collision5_d = M_collision5_q;
          star5_r = 1'h0;
          star5_g = 1'h0;
          star5_b = 1'h0;
        end
      end
      if (M_collision6_q == 1'h0) begin
        M_collision6_d = M_ball_active & M_star6_active | M_ball1_active & M_star6_active;
        star6_r = M_star6_red;
        star6_g = M_star6_green;
        star6_b = M_star6_blue;
      end else begin
        if (M_collision6_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision6_d = M_collision6_q + 1'h1;
          star6_r = 1'h0;
          star6_g = 1'h0;
          star6_b = 1'h0;
        end else begin
          M_collision6_d = M_collision6_q;
          star6_r = 1'h0;
          star6_g = 1'h0;
          star6_b = 1'h0;
        end
      end
      if (M_collision7_q == 1'h0) begin
        M_collision7_d = M_ball_active & M_star7_active | M_ball1_active & M_star7_active;
        star7_r = M_star7_red;
        star7_g = M_star7_green;
        star7_b = M_star7_blue;
      end else begin
        if (M_collision7_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision7_d = M_collision7_q + 1'h1;
          star7_r = 1'h0;
          star7_g = 1'h0;
          star7_b = 1'h0;
        end else begin
          M_collision7_d = M_collision7_q;
          star7_r = 1'h0;
          star7_g = 1'h0;
          star7_b = 1'h0;
        end
      end
      if (M_collision8_q == 1'h0) begin
        M_collision8_d = M_ball_active & M_star8_active | M_ball1_active & M_star8_active;
        star8_r = M_star8_red;
        star8_g = M_star8_green;
        star8_b = M_star8_blue;
      end else begin
        if (M_collision8_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision8_d = M_collision8_q + 1'h1;
          star8_r = 1'h0;
          star8_g = 1'h0;
          star8_b = 1'h0;
        end else begin
          M_collision8_d = M_collision8_q;
          star8_r = 1'h0;
          star8_g = 1'h0;
          star8_b = 1'h0;
        end
      end
      if (M_collision9_q == 1'h0) begin
        M_collision9_d = M_ball_active & M_star9_active | M_ball1_active & M_star9_active;
        star9_r = M_star9_red;
        star9_g = M_star9_green;
        star9_b = M_star9_blue;
      end else begin
        if (M_collision9_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision9_d = M_collision9_q + 1'h1;
          star9_r = 1'h0;
          star9_g = 1'h0;
          star9_b = 1'h0;
        end else begin
          M_collision9_d = M_collision9_q;
          star9_r = 1'h0;
          star9_g = 1'h0;
          star9_b = 1'h0;
        end
      end
      if (M_collision10_q == 1'h0) begin
        M_collision10_d = M_ball_active & M_star10_active | M_ball1_active & M_star10_active;
        star10_r = M_star10_red;
        star10_g = M_star10_green;
        star10_b = M_star10_blue;
      end else begin
        if (M_collision10_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision10_d = M_collision10_q + 1'h1;
          star10_r = 1'h0;
          star10_g = 1'h0;
          star10_b = 1'h0;
        end else begin
          M_collision10_d = M_collision10_q;
          star10_r = 1'h0;
          star10_g = 1'h0;
          star10_b = 1'h0;
        end
      end
      if (M_collision11_q == 1'h0) begin
        M_collision11_d = M_ball_active & M_star11_active | M_ball1_active & M_star11_active;
        star11_r = M_star11_red;
        star11_g = M_star11_green;
        star11_b = M_star11_blue;
      end else begin
        if (M_collision11_q == 1'h1) begin
          M_stars_d = M_stars_q + 1'h1;
          M_collision11_d = M_collision11_q + 1'h1;
          star11_r = 1'h0;
          star11_g = 1'h0;
          star11_b = 1'h0;
        end else begin
          M_collision11_d = M_collision11_q;
          star11_r = 1'h0;
          star11_g = 1'h0;
          star11_b = 1'h0;
        end
      end
      if (M_ball01_collision_q == 1'h0) begin
        M_ball01_collision_d = M_ball_active & M_ball1_active & M_ball_moving;
      end else begin
        M_ball01_collision_d = M_ball01_collision_q;
        M_ball1_destroyed_d = 1'h1;
      end
      if (M_ball10_collision_q == 1'h0) begin
        M_ball10_collision_d = M_ball1_active & M_ball_active & M_ball1_moving;
      end else begin
        M_ball10_collision_d = M_ball10_collision_q;
        M_ball_destroyed_d = 1'h1;
      end
      if (M_ball_destroyed_q == 1'h0) begin
        ball_r = M_ball_red;
        ball_g = M_ball_green;
        ball_b = M_ball_blue;
      end else begin
        ball_r = 1'h0;
        ball_g = 1'h0;
        ball_b = 1'h0;
      end
      if (M_ball1_destroyed_q == 1'h0) begin
        ball1_r = M_ball1_red;
        ball1_g = M_ball1_green;
        ball1_b = M_ball1_blue;
      end else begin
        ball1_r = 1'h0;
        ball1_g = 1'h0;
        ball1_b = 1'h0;
      end
      if (M_stars_q == 4'hc) begin
        pass = 1'h1;
      end else begin
        pass = 1'h0;
      end
      r = M_grid_red | ball_r | ball1_r | star_r | star1_r | star2_r | star3_r | star4_r | star5_r | star6_r | star7_r | star8_r | star9_r | star10_r | star11_r;
      g = M_grid_green | ball_g | ball1_g | star_g | star1_g | star2_g | star3_g | star4_g | star5_g | star6_g | star7_g | star8_g | star9_g | star10_g | star11_g;
      b = M_grid_blue | ball_b | ball1_b | star_b | star1_b | star2_b | star3_b | star4_b | star5_b | star6_b | star7_b | star8_b | star9_b | star10_b | star11_b;
    end else begin
      M_ball_on = 1'h0;
      M_ball1_on = 1'h0;
      r = 1'h0;
      g = 1'h0;
      b = 1'h0;
      M_collision_d = 1'h0;
      M_collision1_d = 1'h0;
      M_collision2_d = 1'h0;
      M_collision3_d = 1'h0;
      M_collision4_d = 1'h0;
      M_collision5_d = 1'h0;
      M_collision6_d = 1'h0;
      M_collision7_d = 1'h0;
      M_collision8_d = 1'h0;
      M_collision9_d = 1'h0;
      M_collision10_d = 1'h0;
      M_collision11_d = 1'h0;
      M_stars_d = 1'h0;
      M_ball_reset = 1'h1;
      M_ball1_reset = 1'h1;
      pass = 1'h0;
      M_current_ball_d = 1'h0;
      M_ball01_collision_d = 1'h0;
      M_ball10_collision_d = 1'h0;
      M_ball_destroyed_d = 1'h0;
      M_ball1_destroyed_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pixel_reg_q <= 1'h0;
      M_grid_change_q <= 1'h0;
      M_collision_q <= 1'h0;
      M_collision1_q <= 1'h0;
      M_collision2_q <= 1'h0;
      M_collision3_q <= 1'h0;
      M_collision4_q <= 1'h0;
      M_collision5_q <= 1'h0;
      M_collision6_q <= 1'h0;
      M_collision7_q <= 1'h0;
      M_collision8_q <= 1'h0;
      M_collision9_q <= 1'h0;
      M_collision10_q <= 1'h0;
      M_collision11_q <= 1'h0;
      M_stars_q <= 1'h0;
      M_counter_q <= 1'h0;
      M_current_ball_q <= 1'h0;
      M_ball01_collision_q <= 1'h0;
      M_ball10_collision_q <= 1'h0;
      M_ball_destroyed_q <= 1'h0;
      M_ball1_destroyed_q <= 1'h0;
      M_ball_selected_q <= 1'h0;
    end else begin
      M_pixel_reg_q <= M_pixel_reg_d;
      M_grid_change_q <= M_grid_change_d;
      M_collision_q <= M_collision_d;
      M_collision1_q <= M_collision1_d;
      M_collision2_q <= M_collision2_d;
      M_collision3_q <= M_collision3_d;
      M_collision4_q <= M_collision4_d;
      M_collision5_q <= M_collision5_d;
      M_collision6_q <= M_collision6_d;
      M_collision7_q <= M_collision7_d;
      M_collision8_q <= M_collision8_d;
      M_collision9_q <= M_collision9_d;
      M_collision10_q <= M_collision10_d;
      M_collision11_q <= M_collision11_d;
      M_stars_q <= M_stars_d;
      M_counter_q <= M_counter_d;
      M_current_ball_q <= M_current_ball_d;
      M_ball01_collision_q <= M_ball01_collision_d;
      M_ball10_collision_q <= M_ball10_collision_d;
      M_ball_destroyed_q <= M_ball_destroyed_d;
      M_ball1_destroyed_q <= M_ball1_destroyed_d;
      M_ball_selected_q <= M_ball_selected_d;
    end
  end
  
endmodule
